### ISSUE TITLE
Update setup information

### ISSUE THREAD

**Issue by amessinger** [njoyard/realease#6]
The Circle CI job example lacks a

```yaml
steps:
  - attach_workspace:
      at: .
```

right now, the script can't find the `package.json` file
